### ISSUE TITLE
Unclear on how to run

### ISSUE THREAD

**Issue by MattPlum** [Vyiel/Advanced-Caesar#1]
Can you please offer an example input on how to run this program?

I am trying "python main.p -e" like it says, but it keeps saying argument error

**Comment by Vyiel** [comment]
Hi, Thanks.
Wrote this eons ago and I myself forgot the ways with it. The code I see dictates, We have to give the encrypt the message with the -e switch along with the key with -k.

Usage I think: filename.py -e "C:\\users\name\abc.txt" -k "password"

**Comment by MattPlum** [comment]
Oh yes that worked, thank you very much for responding!

**Comment by Vyiel** [comment]
You are very much welcome.
